---
title: "Spotify-charts"
author: "Jakob Liebmann"
date: "9 April 2020"
output:
  html_document:
    toc: true
    toc_float: true
    df_print: paged
    code_folding: show  
    theme: united
    highlight: tango
    number_sections: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	message = FALSE,
	warning = FALSE
)
```

# Getting data
```{r}
library(tidyverse)
# Testing one download
download <- read_csv("https://spotifycharts.com/regional/global/daily/2020-04-06/download", 
    col_types = cols(Position = col_integer(), 
        Streams = col_integer()), skip = 1)
head(download)

# Examples
# ========
# https://spotifycharts.com/regional/global/daily/2020-04-06/download
# https://spotifycharts.com/regional/de/weekly/2020-03-20--2020-03-27/download

```

# Write a function
```{r}
getcharts <- function(country)
{
  url<- paste0("https://spotifycharts.com/regional/", country, "/daily/2020-04-05/download")
  print(paste0("Daten werden bezogen: ",url))
  df <- read_csv(url, col_types = cols(Position = col_integer(), Streams = col_integer()), skip = 1)
  df<- df%>%
    mutate(country = country)
  return(df)
  }
returndownload<-getcharts("de")

```

# Map the function
```{r}
library(purrr)
countrylist<-c("de","fr","gb","us")
mappeddownload<-countrylist%>%
  map(getcharts)%>%
  bind_rows()
mappeddownload[199:202, ]
```

# For loop
```{r}
loopeddownload <- tibble()
for (country in countrylist) {
  print(paste0("Getting data for: ",country))
  ifelse(length(loopeddownload)==0,
          loopeddownload<-getcharts(country),
          loopeddownload<-loopeddownload %>% add_row(getcharts(country)))
}

# Comment: the loop is more intuitive, the mapping easier to implement
```

